import URL from '../models/url.model.mjs';
import express from "express";
const router = express.Router();

// Route to show the homepage with all URLs
router.get("/",async (req,res) => {
    // onlt the URL shown to the User generated by the corresponging user
    if(!req.user) return res.redirect("/login");
    const allUrls = await URL.find({
        createdBy: req.user._id
    });
    return res.render("home.view.ejs",{ urls : allUrls });
});

// Route to show the sign-up page
router.get("/userSignup",async (req,res) => {
    return res.render("signup.view.ejs");
})

// Route to show the login page
router.get("/userlogin",async (req,res) => {
    return res.render("login.view.ejs");
})

export default router;